### PR TITLE
Tag static-libs artefact as such in metadata

### PR DESCRIPTION
**Pull request by jerboaa**
See also: https://github.com/adoptium/temurin-build/issues/2699

Should get out of draft once/if https://github.com/adoptium/temurin-build/pull/2725 gets merged.

### CODE REVIEW

**Comment by jerboaa** [comment]
> Seems OK, but needs a full pipeline run

@karianna Thanks. Can you explain what a "full pipeline run" means? Is that needed before or after this is integrated?

**Comment by karianna** [comment]
> > Seems OK, but needs a full pipeline run
> 
> @karianna Thanks. Can you explain what a "full pipeline run" means? Is that needed before or after this is integrated?

I think it can go after - it's not harmful per se

**Review by tellison — APPROVED** [review]

**Comment by sxa** [comment]
> Seems OK, but needs a full pipeline run

@jerboaa I've just kicked off https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1677 so we'll be able to see the output of the jobs run from that run. If you can't see that first link, the individual jobs in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/ are the ones that have the artefacts accessible in them at the end.

**Comment by jerboaa** [comment]
@sxa Thanks very much!

**Pull request merged**
