### PR TITLE
Update arm64 to aarch64

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
related: adoptium/TKG#182 (comment), https://github.com/adoptium/aqa-tests/issues/2501

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Comment by llxia** [comment]
run tests

**Comment by llxia** [comment]
@smlambert could you run PR build? I do not think I have permission.

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
