### PR TITLE
feat: add buildRef ciRef helperRef for tag/branch from temurin-build ci-jenkins-pipeline and jenkins-helper

### PR DESCRIPTION
**Pull request by zdtsw**
when openjdk-pipeline trigger downstream job it only passing down BUILD_CONFIGURATION and NODE_LABEL
so to overwrite defaultsJson from openjdk-pipeline wont make changes in the downstream job. 
https://github.com/adoptium/temurin-build/issues/3103#issuecomment-1261996254

This PR is only to add 3 new parameters in the jenkins job (build parameters)  when generate new pipeline and downstream jobs, it will get there.
This PR does not handle logic of passing down such new parameters to the downstream job. The real part to pass down the values of these 3 are done in https://github.com/adoptium/jenkins-helper/pull/41 
=> these two PR:s will make the placeholder to chain two parts

This PR does not handle logic to overwrite the default values in the defaultsJson of downstream job.

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by zdtsw** [comment]
> #  PR TESTER RESULT 
> negative_squared_cross_mark Some pipelines failed or the job was aborted! negative_squared_cross_mark _See the `pipeline-build-check` below for more information..._

some builds are failed, because of "No space left on device"

**Comment by karianna** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
