### PR TITLE
postBuild plugin manager only available in postBuild groovy

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
pipeline builds broken as postBuild plugin "manager" is only available in postBuild groovy scripts
https://ci.adoptium.net/job/build-scripts/job/openjdk17-pipeline/899/console
```
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: manager for class: Builder
```

I've commented out the build summary annotation for now

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
Just to be clear - this is a partial revert of https://github.com/adoptium/ci-jenkins-pipelines/pull/923 if I'm reading it right - it would be good to note which functionality will be lost from that original PR when this is merged. I suggest @sophia-guo reviews it too to ensure she is aware.

**Comment by andrew-m-leonard** [comment]
> Just to be clear - this is a partial revert of #923 if I'm reading it right - it would be good to note which functionality will be lost from that original PR when this is merged. I suggest @sophia-guo reviews it too to ensure she is aware.

Correct, it's just the build summary label text that will be missing, instead i've put an "echo" with the same information

**Review by sxa — APPROVED** [review]
Approving so this can go in for tonight's builds - if @sophia-guo has any objections we can address them afterwards, but this is causing a build break.

**Comment by sophia-guo** [comment]
I will create a PR to fix this. As the echo only shows the message of link in console output instead of a hyperlink in pipeline job description.

**Comment by sophia-guo** [comment]
Should be a simple update manager --> context.manager.

**Comment by sophia-guo** [comment]
I have tested the update `manager --> context.manager.` works. I will do the update together with the PR for #926

**Comment by andrew-m-leonard** [comment]
> I have tested the update `manager --> context.manager.` works. I will do the update together with the PR for #926

@sophia-guo ah good.
Another thing i've noticed from the overnight beta builds, is it's being called for non-release builds which is probably fine as provides a good test of it, but it's failing as non-release publishes need a TIMESTAMP field: https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8236/

**Comment by sophia-guo** [comment]
@andrew-m-leonard interesting. Ah, switch between https://github.com/adoptium/ci-jenkins-pipelines/pull/923/files and https://github.com/adoptium/ci-jenkins-pipelines/pull/916, forgot the condition if (release). The release_tool build was called  platform first and then after all jdks are done release_tool build was called again (this is the final one and correct one). This failed release_tool build per platform but won't affect the final one. No worries about the publish but confused and also waste build resources. This will also be fixed by https://github.com/adoptium/ci-jenkins-pipelines/pull/932

**Pull request merged**
