### PR TITLE
feat: trim String input from build job

### PR DESCRIPTION
**Pull request by zdtsw**
- use String trim() on String type input

Fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/238

### CODE REVIEW

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
@andrew-m-leonard could you trigger "test" on this one? it is straight solution, without any complicated new method execution.

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by zdtsw** [comment]
> @zdtsw some of the builds failed, but not sure if related to your change? eg: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/3/
> 
> ```
> 14:18:28  Execution error: java.lang.NullPointerException: Cannot invoke method contains() on null object
> [Pipeline] echo
> 14:18:28  java.lang.NullPointerException: Cannot invoke method contains() on null object
> 14:18:28  	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
> 14:18:28  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
> 14:18:28  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
> 14:18:28  	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
> 14:18:28  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
> 14:18:28  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
> 14:18:28  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
> 14:18:28  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
> 14:18:28  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
> 14:18:28  	at Build.buildScripts(Script2.groovy:1344)
> 14:18:28  	at ___cps.transform___(Native Method)
> 14:18:28  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
> 14:18:28  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
> 14:18:28  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
> 14:18:28  	at jdk.internal.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)
> 14:18:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 14:18:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 14:18:28  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
> 14:18:28  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
> ```

Thanks Andrew!
it is my change, a check on a "" String leads to null which in case when we do not set BUILD_ARGS then the contains() fails. I am fixing it and adding a test case for it.

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM - tests pass

**Review by andrew-m-leonard — APPROVED** [review]

**Pull request merged**
