### PR TITLE
fix: docker SHA1 passing down to buildscript()

### PR DESCRIPTION
**Pull request by zdtsw**
# problem
in build() => call buildscript() => 
call `build-farm/make-adopt-build-farm.sh`  which including all SBOM steps (e.g read docker.txt)
then call writeMetadata (which write docker SHA1 into docker.txt)
thats why in the SBOM step it does not get value from docker.txt
```
  "metadata" : {
    "timestamp" : "2022-07-13T09:23:03Z",
    "tools" : [
      {
        "name" : "ALSA",
        "version" : "https://ftp.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.1.6.tar.bz2"
      },
      {
        "name" : "FreeType",
        "version" : "N.A"
      },
      {
        "name" : "FreeMarker",
        "version" : "N.A"
      },
      {
        "name" : "Docker image SHA1",
        "version" : "N.A"
      }
```
# solution
in build() when we get docker digest, write into docker.txt
then call buildscript()

Ref https://github.com/adoptium/temurin-build/pull/3045

test run: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk18u/job/jdk18u-alpine-linux-x64-temurin/60/console
```
10:03:36  $ docker run -t -d -u 1000:1000 -e BUILDIMAGESHA=adoptopenjdk/alpine3_build_image@sha256:0d85897589f0e360e876053b97a1756f4583afd816d2ccec37839652d4818289
10:03:36   -w /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin -v /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin:/home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin:rw,z -v /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin@tmp:/home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** adoptopenjdk/alpine3_build_image cat
```
then temubin-build only need to get env variable BUILDIMAGESHA as input for docker.txt

# test
pr-test in https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk19u/
- windows result:
```
      {
        "name" : "Use Docker for build",
        "value" : "false"
      }
```
- mac result: 
```
 {
        "name" : "Use Docker for build",
        "value" : "false"
      }
```
- alpinelinux result:
```
 {
        "name" : "Docker image SHA1",
        "version" : "adoptopenjdk/alpine3_build_image@sha256:5ae1d40cb6b3cc40e1866437729b0a285e6d76598d558da476f76b98242a3826"
      }
{
        "name" : "Use Docker for build",
        "value" : "true"
      }
```

### CODE REVIEW

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
run tests

**Comment by zdtsw** [comment]
> #  PR TESTER RESULT 
> negative_squared_cross_mark Some pipelines failed or the job was aborted! negative_squared_cross_mark _See the `pipeline-build-check` below for more information..._

got what i needed:
` docker run -t -d -u 1000:1000 -e BUILDIMAGESHA=adoptopenjdk/alpine3_build_image@sha256:0d85897589f0e360e876053b97a1756f4583afd816d2ccec37839652d4818289
09:42:19   -w /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin -v /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin:/home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin:rw,z -v /home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin@tmp:/home/adoptopenjdk/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-alpine-linux-x64-temurin@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** adoptopenjdk/alpine3_build_image cat
09:42:20  $ docker top 443355d4e05e9d42716bc4ee1c1e875cec4821a1aa01134473a6f5a30bce8c95 -eo pid,comm`

also when do `env`
```
09:42:24  JENKINS_SERVER_COOKIE=durable-33bd8d0e4ae6dc829b0862b2c23c75094a45c63811dba02ce0aa331943334c93
09:42:24  JDKLATEST_BOOT_DIR=/usr/lib/jvm/zulu18
09:42:24  BUILDIMAGESHA=adoptopenjdk/alpine3_build_image@sha256:0d85897589f0e360e876053b97a1756f4583afd816d2ccec37839652d4818289
```

**Comment by zdtsw** [comment]
run tests

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by zdtsw** [comment]
run tests quick 19

**Review by steelhead31 — APPROVED** [review]
LGTM

**Pull request merged**
