### PR TITLE
Remote trigger with SETUP_JCK_RUN parameter

### PR DESCRIPTION
**Pull request by sophia-guo**
Release SETUP_JCK_RUN=true, weekly or evaluation weekly SETUP_JCK_RUN=false

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Related or depends on https://github.com/adoptium/aqa-tests/pull/4239

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@sophia-guo Still needed?

**Comment by sophia-guo** [comment]
This is to limit setup_jck_run to release only. If we'd like to also keep it to weekly run the PR will not need any more. @smlambert idea?

**Comment by smlambert** [comment]
Release only is sufficient, as we will also get it when doing a 'dry-run' release pipeline.  Thanks @sophia-guo !

**Pull request merged**
