### PR TITLE
Add extended buildinfo to metadata

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Extensions for re-recreatable builds as per: https://github.com/adoptium/temurin-build/issues/2594#issuecomment-841199132

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Depends on PR https://github.com/adoptium/temurin-build/pull/2636

**Comment by karianna** [comment]
@andrew-m-leonard https://github.com/adoptium/temurin-build/pull/2636 has landed

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard [adoptium/temurin-build#2636](https://github.com/adoptium/temurin-build/pull/2636) has landed

@thanks @karianna

**Comment by karianna** [comment]
> > @andrew-m-leonard [adoptium/temurin-build#2636](https://github.com/adoptium/temurin-build/pull/2636) has landed
> 
> @thanks @karianna

Does that mean this is ready for review?

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
@karianna yes, once ive run the tests

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Seems unrelated but linux 11 x64 Openj9 build failed:

```
13:17:26  /bin/sh: CCACHE_COMPRESS=1: command not found
13:17:26  Makefile:9019: recipe for target 'test/rsa_complex' failed
13:17:26  gmake[5]: *** [test/rsa_complex] Error 127
13:17:26  gmake[5]: *** Waiting for unfinished jobs....
13:17:26  Makefile:174: recipe for target 'all' failed
```

**Comment by AdamBrousseau** [comment]
That failure is due to https://github.com/adoptium/infrastructure/pull/2084
Investigation is needed as to why openssl won't compile.

**Pull request merged**
