### PR TITLE
Disable tests during April release week

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
Request TSC approval

**Review by M-Davies — APPROVED** [review]

**Comment by sxa** [comment]
I got thrown by the fact this didn't change the value in `config_regeneration.groovy` as we have in previous cycles but it looks like https://github.com/adoptium/ci-jenkins-pipelines/pull/102 likely removed the need for that so it should be ok 👍🏻

**Review by sxa — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Review by gdams — APPROVED** [review]

**Comment by sophia-guo** [comment]
I believe if we still need to manually trigger regenerating build jobs otherwise this change won't work. 

By regenerating jobs I mean:
 https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/
 https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk8u/
 https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk11u/
 https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk16u/

**Pull request merged**
