### PR TITLE
Verify Windows and Mac Signing signatures in all executables and installers

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/temurin-build/issues/3494

For Temurin builds, verify that for Windows and Mac platforms all the following are correctly signed with a non-adhoc Signature:
- Mac:
  - Within JMODs executable format files
  - jdk|jre/bin executable format files
  - *.pkg installers (also verify Notarized)
- Windows:
  - Within JMODs all *.exe/*.dll executable files
  -  jdk|jre/bin all *.exe/*.dll executable files
  - *.msi installers

### CODE REVIEW

**Comment by karianna** [comment]
@andrew-m-leonard linter not happy

**Comment by andrew-m-leonard** [comment]
run tests

**Review by adamfarley — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Digging into the pipeline failures - looks like Mac Os X signing failures e.g.,

Error: executable is 'adhoc' Signed: unpacked/jdk/expanded_java.management.jmod/lib/libmanagement.dylib
FAILURE: The following 194 executables are not signed correctly:
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jwebserver
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jfr
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/rmiregistry

**Review by karianna — DISMISSED** [review]
Error: executable is 'adhoc' Signed: unpacked/jdk/expanded_java.management.jmod/lib/libmanagement.dylib
FAILURE: The following 194 executables are not signed correctly:
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jwebserver
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jfr
    unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/rmiregistry

**Comment by andrew-m-leonard** [comment]
> Error: executable is 'adhoc' Signed: unpacked/jdk/expanded_java.management.jmod/lib/libmanagement.dylib FAILURE: The following 194 executables are not signed correctly: unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jwebserver unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/jfr unpacked/jre/jdk-21.0.1+12-jre/Contents/Home/bin/rmiregistry

@karianna  So yeah, the pr-tester does not Eclipse "Sign" the dylibs, so it's actually accurate, but we obviously don't want the pr-tester to fail! So I shall have to exclude the sign_verification from the pr-tester.

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
@karianna checks look all good now

**Pull request merged**
