### PR TITLE
Escape '-' literals in patterns

### PR DESCRIPTION
**Pull request by keithc-ca**
The pattern `[.-_]` matches characters `0x2e` through `0x5f` (which includes `[A-Z]`). I don't think that was the intent; `-` must be escaped (or appear first or last in `[]`).

See also #881 and #888.

### CODE REVIEW

**Review by sxa — APPROVED** [review]
Thanks Keith - can you PR the same change against the v2024.01.01 branch too please?

**Review by smlambert — APPROVED** [review]

**Comment by keithc-ca** [comment]
> can you PR the same change against the v2024.01.01 branch too please?

See https://github.com/adoptium/ci-jenkins-pipelines/pull/893.

**Pull request merged**
