### PR TITLE
Enable mac x64 & aarch64 reproduciable comparison build

### LINKED ISSUE #763: Enable jdk17 mac-x64 and mac aarch64 reproducible comparison build
Part of https://github.com/adoptium/temurin-build/issues/3245

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #763 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Depends on https://github.com/adoptium/temurin-build/pull/3443

**Review by smlambert — APPROVED** [review]
and a rebase since this one contains former PR's code

**Comment by karianna** [comment]
> Depends on https://github.com/adoptium/temurin-build/pull/3443

Merged

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Pull request merged**
