### PR TITLE
Add jdk21 to build health report

### PR DESCRIPTION
**Pull request by adamfarley**

### CODE REVIEW

**Comment by adamfarley** [comment]
Test run here: https://ci.adoptium.net/job/nightlyBuildAndTestStats_temurin/1059/

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by sxa — COMMENTED** [review]
Can we make sure that this part of the process is documented in https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#openjdk-new-major-release-process - probably using a link to this PR as an example.

**Comment by adamfarley** [comment]
> Can we make sure that this part of the process is documented in https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#openjdk-new-major-release-process - probably using a link to this PR as an example.

Sure. I'll hold off until John Oliver has replied to [this Slack message](https://adoptium.slack.com/archives/C09NW3L2J/p1684319922924299?thread_ts=1684237345.823859&cid=C09NW3L2J) with the details of his changes to api.adoptium.net.

**Comment by sxa** [comment]
From the thread it seems that  https://github.com/adoptium/api.adoptium.net/blob/bda17356dae38e4a36a2aa2aef9bec3b5e9e4275/adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Versions.kt#L5 needs to be updated too so that should be done and added to the docs as well (The immediate fix that was applied to resolve this was to override the java `LATEST_JAVA_VERSION` property in the API instead of updating that file)

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Comment by sxa** [comment]
API change PR: https://github.com/adoptium/api.adoptium.net/pull/578

**Review by sxa — APPROVED** [review]
Approving on the basis that the documentation gets done, as that will need to be in a different repository anyway so will not be part of this PR.

**Review by gdams — APPROVED** [review]

**Review by gdams — APPROVED** [review]

**Comment by adamfarley** [comment]
Note: The docs change mentioned above was carried out here: https://github.com/adoptium/temurin-build/pull/3360

**Pull request merged**
