### PR TITLE
chore: prep for 2022 Oct CPU release to disable nightly test

### PR DESCRIPTION
**Pull request by zdtsw**
Disable Nightly test for 2022 Oct CPU release

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by zdtsw** [comment]
now i start to think if this can be done now.....
in https://github.com/adoptium/ci-jenkins-pipelines/pull/424 if we set enableTests = false, then coming weekly wont triggere remote TCK jobs.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by zdtsw** [comment]
> now i start to think if this can be done.... in #424 if we set enableTests = false, then coming weekly wont triggere remote TCK jobs. and even the release build wont do the remote triggere.
> 
> So if we want to stop nightly run (enableTest=false) we can only merge this PR right after we have build our release binaries for all supported jdk versions.

after discussion, we should have this one merge now
when we run weekly or the official release we can set the input to False for the build

**Comment by sophia-guo** [comment]
> when we run weekly or the official release we can set the input to False for the build

For the official release we can set the input to **true** for the build

**Pull request merged**
