### PR TITLE
fix failing jtreg build job

### PR DESCRIPTION
**Pull request by gdams**
fixes: https://github.com/adoptium/temurin-build/issues/2697

### CODE REVIEW

**Comment by karianna** [comment]
Were you able to manually test this?

**Comment by gdams** [comment]
> Were you able to manually test this?

Yeah I've confirmed that this fixes the failure

**Comment by karianna** [comment]
PMC approved.  We may need the latest jtreg for 17 release debug

**Review by karianna — APPROVED** [review]
LGTM

**Review by jerboaa — APPROVED** [review]
LGTM

**Pull request merged**
