### PR TITLE
Ensure any old openjdk build directory is removed before building

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
The openjdk build output directory may exist from a previous build if it was aborted or purposely kept.
It must always be deleted prior to a new build.

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by sophia-guo — CHANGES_REQUESTED** [review]
Does the code https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L1792-L1817 do the clean?

**Comment by sophia-guo** [comment]
Wondered if this should be done in temurin-build?

**Comment by andrew-m-leonard** [comment]
> Wondered if this should be done in temurin-build?

So no, because a user may have specified a user openjdk build folder that maybe by accident is some location they don't want to delete like /home !

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by sophia-guo** [comment]
If cleanWorkspace=true [context.WORKSPACE will be cleaned up](https://github.com/adoptium/ci-jenkins-pipelines/blob/904ffdc6263bfe12353e7313d32d56789b06a209/pipelines/build/common/openjdk_build_pipeline.groovy#L1514) include openjdk_build_dir(under WORKSPACE). Otherwise openjdk_build_dir will not be cleaned up.

This pr will cleanup openjdk_build_dir(under WORKSPACE) even if  cleanWorkspace=false. However any other files or directory under the WORKSPACE will not be cleaned up if  cleanWorkspace=false. 

Just curious any reason we don't do the cleanWorkspace by default [CLEAN_WORKSPACE": false](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-x64-temurin/197/parameters/ )?

**Comment by andrew-m-leonard** [comment]
> If cleanWorkspace=true [context.WORKSPACE will be cleaned up](https://github.com/adoptium/ci-jenkins-pipelines/blob/904ffdc6263bfe12353e7313d32d56789b06a209/pipelines/build/common/openjdk_build_pipeline.groovy#L1514) include openjdk_build_dir(under WORKSPACE). Otherwise openjdk_build_dir will not be cleaned up.
> 
> This pr will cleanup openjdk_build_dir(under WORKSPACE) even if cleanWorkspace=false. However any other files or directory under the WORKSPACE will not be cleaned up if cleanWorkspace=false.
> 
> Just curious any reason we don't do the cleanWorkspace by default [CLEAN_WORKSPACE": false](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-x64-temurin/197/parameters/)?

We have always not cleaned the WORKSPACE before a build by default for nightly/weekly builds, the reason is to save time in having to re-clone the openjdk src repository(~2Gb) each time.
Release builds do clean WORKSPACE before a build.

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
