### PR TITLE
Use (local) rhel7_build_image for Linux/s390x builds

### PR DESCRIPTION
**Pull request by sxa**
Needs https://github.com/adoptium/ci-jenkins-pipelines/pull/611 merged first
Fixes https://github.com/adoptium/infrastructure/issues/2731

### CODE REVIEW

**Comment by sxa** [comment]
run tests

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
making draft to make sure I don't land before the precuror has landed.

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Pull request merged**
