### PR TITLE
Typo fixes in prTester readme file

### PR DESCRIPTION
**Pull request by AyBims**
Fixes: #454
signed-off-by: Ayomide Adeshina <adeshinaayomide12@yahoo.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
some linter errors still need to fix

**Comment by karianna** [comment]
@AyBims - A few linter issues to fix as Wen mentions.

**Comment by karianna** [comment]
@AyBims Are you able to rebase this PR?

**Pull request merged**
