### PR TITLE
workaround: temp. add  codenarc rules exclude warnings in super-linter to not block GH action check

### PR DESCRIPTION
**Pull request by zdtsw**
this is a workaround for https://github.com/adoptium/ci-jenkins-pipelines/issues/425  to exclude lint warnings
	we should either wait a fix from super-linter or create an issue to clear all these warnings

runs from test: https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/3173733570/jobs/5169675250 

Ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/428

### CODE REVIEW

**Review by karianna — COMMENTED** [review]
Are these agreed linter rules with the team?

**Comment by zdtsw** [comment]
> Are these agreed linter rules with the team?

This is only a workaround to not block ci-jenkins-pipeline.
My plan is to create another issue to fix our linter problem so the goal is to take away these exclude rules.
The reason to add this file is because of the changes happened in super-linter during last weekend, detail: https://github.com/github/super-linter/issues/3391

**Comment by nvuillam** [comment]
@zdtsw most of the rules you disabled can be auto-fixed if you run npm-groovy-lint --fix in your repo :)
You can also use VsCode Groovy Lint to do that from Ui :)

**Comment by zdtsw** [comment]
> @zdtsw most of the rules you disabled can be auto-fixed if you run npm-groovy-lint --fix in your repo :) You can also use VsCode Groovy Lint to do that from Ui :)

thanks @nvuillam ! 
some parts I am able to fix with "--fix" flag, but rest might need more times to fix one after one, e.g NoDef ClassJavadoc etc.

**Comment by nvuillam** [comment]
> > @zdtsw most of the rules you disabled can be auto-fixed if you run npm-groovy-lint --fix in your repo :) You can also use VsCode Groovy Lint to do that from Ui :)
> 
> thanks @nvuillam ! some parts I am able to fix with "--fix" flag, but rest might need more times to fix one after one, e.g NoDef ClassJavadoc etc.

Usually i disable noDef & javaDoc rules imy groovy project :)

I was more referring to style & formatting issues ^^

**Comment by karianna** [comment]
@zdtsw - do we have an issue for fixing the linter items that we can reference from this one?  Then I'm happy to accept.

**Comment by zdtsw** [comment]
> @zdtsw - do we have an issue for fixing the linter items that we can reference from this one? Then I'm happy to accept.

sure https://github.com/adoptium/ci-jenkins-pipelines/issues/428

**Comment by zdtsw** [comment]
> > @zdtsw - do we have an issue for fixing the linter items that we can reference from this one? Then I'm happy to accept.
> 
> sure #428

@andrew-m-leonard and I will try to make a shorter list of exclude list and get other fixed

**Review by karianna — APPROVED** [review]
LGTM

**Review by andrew-m-leonard — APPROVED** [review]

**Pull request merged**
