### PR TITLE
rename all references of AdoptOpenJDK/ci-jenkins-pipelines to Adoptium

### PR DESCRIPTION
**Pull request by gdams**
closes: https://github.com/adoptium/ci-jenkins-pipelines/issues/117

### CODE REVIEW

**Comment by karianna** [comment]
Missed a test or two:

```
RepoHandlerTest > adoptDefaultsGetterReturns() FAILED
    org.opentest4j.AssertionFailedError: expected: <https://github.com/AdoptOpenJDK/ci-jenkins-pipelines.git> but was: <https://github.com/adoptium/ci-jenkins-pipelines.git>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at org.junit.jupiter.api.Assertions$assertEquals$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at RepoHandlerTest.adoptDefaultsGetterReturns(RepoHandlerTest.groovy:25)
```

**Comment by gdams** [comment]
Hmm so the test gets the values from https://raw.githubusercontent.com/adoptium/ci-jenkins-pipelines/master/pipelines/defaults.json which will only change once this PR has been merged.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Pull request merged**
