### PR TITLE
Remove RELEASE_TAG, which has been removed from downstream jobs

### PR DESCRIPTION
**Pull request by sophia-guo**
Related with https://github.com/adoptium/temurin-build/pull/2166/ 
https://github.com/adoptium/aqa-tests/pull/2035

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by karianna** [comment]
Hmm, is this not used by OpenJ9 / Semeru builds or even temurin builds with the _adopt suffix tag?

**Comment by sophia-guo** [comment]
I believe it's not used by Openj9 / Semeru builds @llxia could you confirm that?

What is the builds with _adopt suffix tag? Are we still running them?

**Comment by karianna** [comment]
> I believe it's not used by Openj9 / Semeru builds @llxia could you confirm that?
> 
> What is the builds with _adopt suffix tag? Are we still running them?

I think we can ignore the _adopt suffix tags as that's silently handled now CC @gdams

**Comment by llxia** [comment]
> I believe it's not used by Openj9 / Semeru builds

RELEASE_TAG is removed in aqa-tests repo. I do not think it is used by Openj9 / Semeru builds. FYI @AdamBrousseau

**Comment by sophia-guo** [comment]
@smlambert could you please take a review? Thanks

**Review by smlambert — APPROVED** [review]
LGTM, thanks @sophia-guo !

**Pull request merged**
