### PR TITLE
docs: update README.md with output from generateBuildMatrix.sh

### PR DESCRIPTION
**Pull request by zdtsw**
all "openj9" jobs are cleaned up
refer: https://github.com/zdtsw/ci-jenkins-pipelines/blob/fix/215_2/README.md for better review format

Fix: #215

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by zdtsw** [comment]
@smlambert Can I get a review on this PR?

**Review by smlambert — APPROVED** [review]
thanks @zdtsw !  I reviewed the output more thoroughly than the quite dense code change ... definitely improved 👍

**Comment by smlambert** [comment]
Merging with or without knowing if code freeze lifted as is doc specific.

**Pull request merged**
