### PR TITLE
feat: pass ghprbActualCommit to pr-test openjdkX-pipeline

### PR DESCRIPTION
**Pull request by zdtsw**
main change is in 
pipelines/build/prTester/kick_off_tester.groovy
pipelines/build/prTester/pr_test_pipeline.groovy
pipelines/build/common/openjdk_build_pipeline.groovy => updateGitHubcommitStatus()

 - disable some options which not need for pr-tests
- set ghprbAuthorRepoGitUrl into "USER_REMOTE_CONFIGS" as remote url
- use upstream git repo when update github commit status

rest are: 
- fixed linter error in README
- fixed variable scope problem: `hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: actualJavaVersion for class: PullRequestTestPipeline`

Fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/507

### CODE REVIEW

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 11

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
run tests quick 19

**Comment by zdtsw** [comment]
so the pr-test is passed, but job is set to unstable, need to check which part is not working

**Comment by zdtsw** [comment]
> so the pr-test is passed, but job is set to unstable, need to check which part is not working

it is the "ERROR: [GitHub Commit Status Setter] - https://api.github.com/repos/zdtsw/ci-jenkins-pipelines/statuses/cedaf0b1dd26459200c8f91fabab6eb08d9602a5 {"message":"Not Found","documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}, setting build result to UNSTABLE"

**Comment by zdtsw** [comment]
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk19u/job/jdk19u-linux-aarch64-temurin/ failed with compilation error all others are good
rebuild it

**Comment by zdtsw** [comment]
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk19u/job/jdk19u-linux-aarch64-temurin/10/console passed

**Review by andrew-m-leonard — APPROVED** [review]
Happy if pr tests pass

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Not sure why 19 failed, log seems to think it was successful.

**Comment by zdtsw** [comment]
> Not sure why 19 failed, log seems to think it was successful.

in the first time run, it failed when compile cyclonxdb part, then i re-run the job and it passed.

**Pull request merged**
