### PR TITLE
replace all occurences of openjdk-build with temurin-build

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Review by karianna — CHANGES_REQUESTED** [review]
1 test failure

**Comment by gdams** [comment]
yeah the test failure will be fixed when we merge

**Comment by gdams** [comment]
run tests

**Review by karianna — APPROVED** [review]

**Pull request merged**
