### PR TITLE
Enable SBOM strace for all Linux platforms

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/ci-jenkins-pipelines/issues/1064

Enable SBOM strace for all Linux platforms (except riscv64 which fails in emulation environment)

Note: 
1. temurin aarch64 builds are 160 core, which exhausts memory when using strace, so are throttled to 16 cores.
2. temurin arm32 builds run on 160 core hosts, which exhausts resources when using strace causing very very slow build (8+hours), so are throttled to 4 cores (builds in under 1 hour !).

Also, fix "cleanWorkspaceBuildOutputAfterBuild" so it cleans straceOutput, since it is about 3Gb in size!

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
jdk8u mac fails for un-related issue:
```
12:50:15  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
```

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by karianna** [comment]
@andrew-m-leonard holding off merging since the jdk 11 on Linux went over 8 hours, was this new feature the cause?  not sure :-)

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard holding off merging since the jdk 11 on Linux went over 8 hours, was this new feature the cause? not sure :-)

thanks @karianna yes, so that's interesting, i've just anaylsed why jdk11u x64Linux took so long, and I think it is because it is using ccache, which results in thousands of these effectively unknown package C source being used:
```
18:27:41  /home/jenkins/.ccache/a/8/fd306b20290e3d6fb387593c6b7b5a-140229.o.93ac9f76d35a.84120.3WdDjJ
```
Need to think about that one

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Pull request merged**
