### PR TITLE
fix: auto fix linter Warnings by npm-groovy-lint

### PR DESCRIPTION
**Pull request by zdtsw**
Step one to fix lint Warnings , mostly for indentation.

Ref https://github.com/adoptium/ci-jenkins-pipelines/issues/428

### CODE REVIEW

**Comment by karianna** [comment]
@zdtsw Needs a rebase sorry

**Review by karianna — APPROVED** [review]
LGTM

**Review by karianna — CHANGES_REQUESTED** [review]
@zdtsw Linter still seemed to have some significant errors (unused private methods etc)

**Comment by zdtsw** [comment]
> @zdtsw Linter still seemed to have some significant errors (unused private methods etc)

Yes. these wont be fixed by the "auto fix" ,  we need to do it one by one, listed in https://github.com/adoptium/ci-jenkins-pipelines/issues/428#issuecomment-1268019252

**Review by andrew-m-leonard — APPROVED** [review]
lot of changes, but looks ok I think

**Pull request merged**
