### PR TITLE
Stop passing NODE_LABEL to jobs which don't accept it

### PR DESCRIPTION
**Pull request by sxa**
This will fix many of the errors from https://github.com/adoptium/infrastructure/issues/2774

### CODE REVIEW

**Comment by sxa** [comment]
run tests

**Comment by karianna** [comment]
03:02:31  ERROR: Error during copy and archive artifacts for build job: build-scripts-pr-tester/build-test/jobs/jdk17u/jdk17u-windows-x64-temurin
03:02:31  ERROR: Failed to copy artifacts from build-scripts-pr-tester/build-test/jobs/jdk17u/jdk17u-windows-x64-temurin with filter: workspace/target/*

Not sure if that's an issue or not.

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by sxa** [comment]
Hmmm pipeline build check showing this:
```
09:54:51  [INFO] build name: build-scripts-pr-tester/build-test/jobs/jdk20/jdk20-alpine-linux-x64-temurin
Pausing (Preparing for shutdown)
Resuming build at Thu Mar 30 10:58:55 CEST 2023 after Jenkins restart
[Pipeline] End of Pipeline
java.io.FileNotFoundException: /home/jenkins/.jenkins/jobs/build-scripts-pr-tester/jobs/openjdk-build-pr-tester/builds/1821/program.dat (No such file or directory)
```
Although that was probably impacted by the jenkins maintenance last week. Running again ...

**Comment by sxa** [comment]
run tests

**Comment by sxa** [comment]
Dup of https://github.com/adoptium/ci-jenkins-pipelines/pull/673/commits - closing

**Pull request closed without merging**
