### PR TITLE
Fix jtreg build, clean redundant code

### LINKED ISSUE #165: jtreg artifacts contain incorrect contents
The https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/ job produces several artifacts, some of them contain incorrect contents.   

- jtreg4.2.0 doesn't contain 4.2.0 (see [Slack conversation](https://adoptium.slack.com/archives/C5219G28G/p1623072758038100))
- this job used to produce 5.0.1b but started producing a 6+1 (test.getDependency and job is failing due to this change... was expecting the other version)
- the name of the jtreg 6 file is 'problematic' jtreg--6+1 (and doesn't follow previous naming convention)

The Jenkinsfile and jtreg.sh files are in: https://github.com/adoptium/ci-jenkins-pipelines/tree/master/tools/code-tools

### PR DESCRIPTION
**Pull request by sophia-guo**
Update jtreg6+ use build.sh while jtreg5 use buildall.sh.

Since jtreg5, build script can download and build dependencies. Remove redundant dependent build and jars.

Close #165 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Test
test/jdk/java/lang/invoke/MethodHandles/privateLookupIn/Driver.java with jdk17 works  fine with generated jtreg-6+1.tar.gz ( build with testng7.3).

jtreg5.1-b01.tar.gz works with jdk16 and jdk16- .

**Review by karianna — APPROVED** [review]
LGTM

**Review by tellison — APPROVED** [review]

**Review by jerboaa — APPROVED** [review]
Nice work!

**Comment by sophia-guo** [comment]
@jerboaa Thanks for your instant help!

**Comment by smlambert** [comment]
Thanks @sophia-guo !  Please post an FYI to the build Slack channel with a link to this PR as mentioned in our scrum this morning, to let people know of the change (no longer needing to separately build dependencies, so no longer archiving them on the Jenkins job).  

Shall we hold on merging this to address the test updates needed (in aqa-tests and TKG, tracked in https://github.com/adoptium/aqa-tests/issues/2642)?

**Comment by sophia-guo** [comment]
@smlambert we need first merge this and update tests in TKG and probably aqa-tests. And then trigger the job https://ci.adoptopenjdk.net/view/all/job/test.getDependency/ manually for instant update.

**Pull request merged**
