### PR TITLE
avoid sign_temurin_gpg in non-adopt pipelines

### PR DESCRIPTION
**Pull request by mahdipub**
fixes issue #981  

This is to avoid not adoptium pipelines pick the sign_temurin_gpg

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
Approving it because I assume no downstream user of these pipelines would want this block, though I have not confirmed with anyone about that assumption.

**Review by sxa — COMMENTED** [review]
I'm going to defer to @andrew-m-leonard on this. While I'd be ok with it (and it's something I've done elsewhere) I feel there ought to be a parameter that can be used to determine whether to invoke the signing code.

@AdamBrousseau has suggested a `VARIANT` check as potentially suitable for this in https://github.com/adoptium/ci-jenkins-pipelines/issues/981#issuecomment-2013789159 - I'd be ok with it being `if VARIANT = temurin` as a preference if that's feasible since I don't think we'll ever have a requirement to be doing this on another variant (since Adoptium don't ship anything else)

**Comment by AdamBrousseau** [comment]
There is `ENABLE_SIGNER` param. But we use that to toggle our own signing process. We kick a different job to sign our stuff with presumably different params. If you don't care to sign your OpenJ9 builds we could use variant=temurin here. I figured since you are currently signing your openj9 builds we'd go this route.

**Review by andrew-m-leonard — APPROVED** [review]
Although I feel a new param maybe ideal, we do have precedence for this same check on JENKINS_URL for things like pipeline generation authentication...
So I am good with this.

**Review by sxa — APPROVED** [review]
> Although I feel a new param maybe ideal, we do have precedence for this same check on JENKINS_URL for things like pipeline generation authentication... So I am good with this.

👍🏻 in which case I'll approve too. It's a terrible (IMHO) precedent, and perhaps we should look at going through them all later (I hadn't realised it was in other places too) but I'm ok with this extra 'leak' for now.

**Pull request merged**
