### PR TITLE
Add bisheng jdk8 configuration on Aarch64Linux to enable kae

### PR DESCRIPTION
**Pull request by eapenzhan**
As the title says, just add a configuration.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by sxa — CHANGES_REQUESTED** [review]
I've just tried to build with that option and it seems to result in compilation failures - is that expected at the moment? These are the first errors but there are a lot more in the log - is this expected? I would be reluctant to approve this if it will destabilise the builds
```
/home/sxa/openjdk-build/build-farm/workspace/build/src/jdk/src/share/native/java/lang/fdlibm/src/e_asin.c: In function '__j__ieee754_asin':
/home/sxa/openjdk-build/build-farm/workspace/build/src/jdk/src/share/native/java/lang/fdlibm/src/e_asin.c:101:15: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
             } else
               ^~~~
```

**Comment by eapenzhan** [comment]
> I've just tried to build with that option and it seems to result in compilation failures - is that expected at the moment? These are the first errors but there are a lot more in the log - is this expected? I would be reluctant to approve this if it will destabilise the builds
> 
> ```
> /home/sxa/openjdk-build/build-farm/workspace/build/src/jdk/src/share/native/java/lang/fdlibm/src/e_asin.c: In function '__j__ieee754_asin':
> /home/sxa/openjdk-build/build-farm/workspace/build/src/jdk/src/share/native/java/lang/fdlibm/src/e_asin.c:101:15: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
>              } else
>                ^~~~
> ```

could I check the full log?

**Review by sxa — APPROVED** [review]
Retried and this LGTM now. And my turn to apologise for not getting back to this (release cycles got in the way and this got missed!)

**Pull request merged**
