### PR TITLE
Enable Temurin build of x64/ppc64le/aarch64/s390x Linux for jdk-21+ using Adoptium gcc 11.3.0 DevKit

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Enable Temurin build of x64/ppc64le/aarch64/s390x Linux for jdk-21+ using Adoptium DevKit
release:
- x64/ppc64le : gcc-11.3.0-Centos7.9.2009-b02
- aarch64 : gcc-11.3.0-Centos7.6.1810-b02
- s390x : s390x-on-s390x.RH7

aarch64 uses Centos7.6 as it is the matching latest version for RHEL7.

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — APPROVED** [review]

**Review by sxa — COMMENTED** [review]
We should be able to add in a `--with-devkit` parameter for s390x along with this too assuming some of my test runs overnight work as expected :-)

Also when https://github.com/adoptium/infrastructure/pull/3488 goes in and the build images get built the same will be possible on these three platforms too.

**Comment by andrew-m-leonard** [comment]
> We should be able to add in a `--with-devkit` parameter for s390x along with this too assuming some of my test runs overnight work as expected :-)
> 
> Also when [adoptium/infrastructure#3488](https://github.com/adoptium/infrastructure/pull/3488) goes in and the build images get built the same will be possible on these three platforms too.

@sxa  That's great.
Since s390x won't be downloaded from devkit-runtimes, a PR will be needed to update --use-adoptium-devkit to search in /usr/local/devkit and verify tag, ditto for picking up the local x64/ppc64le/aarch64 ones..

Lets get this merged, and I can enable the later in a new PR.

**Review by sxa — APPROVED** [review]
LGTM. Note to reviewers - the s390x naming WILL be improved later for consistency but this will allow us to get parity for now.

**Pull request merged**
