### PR TITLE
Update test list logic

### LINKED ISSUE #894: Cannot invoke method unique() on null object affecting jdk11u x64 release pipeline
This pr, https://github.com/adoptium/ci-jenkins-pipelines/pull/886, was merged to the Jan 2024 [release branch](https://github.com/adoptium/ci-jenkins-pipelines/tree/v2024.01.01) to resolve a build error 

```
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: f2a762ce-4e70-4bdf-a9db-fb100d258499
java.lang.NullPointerException: Cannot invoke method unique() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
```
See https://ci.adoptium.net/job/build-scripts/job/release-openjdk11-pipeline/28/console

This error did not affect non release builds so it needs to be discussed as to whether this commit should be in master and a proper investigation is needed as to the cause of the error

### PR DESCRIPTION
**Pull request by sophia-guo**
close #894 

Update test list logic - if no testlist for specific test type is defined  set as default

update linux x64 jdk11 test configuration to be default

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by smlambert — APPROVED** [review]
LGTM, but can you please take a look at a somewhat related PR https://github.com/adoptium/ci-jenkins-pipelines/pull/880/ to see if it will play nice with these changes?

**Comment by sophia-guo** [comment]
This change should merge first, otherwise #880 will cause similar issue as #894 for non-releases.

**Comment by karianna** [comment]
I this needed during the release?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/ci-jenkins-pipelines/pull/896#issuecomment-1911316876 - the release is completed, we should be lifting the code freeze and starting to move these post-release improvements in.  :)

**Pull request merged**
