### PR TITLE
switch windows builds to use docker image from azurecr

### PR DESCRIPTION
**Pull request by sxa**
Currently the windows container builds are using a local container image on the machine which is not scalable and takes a while to update. This change will pull from the private azure container registry with a credential where we are storing the container images.

Partially fixes https://github.com/adoptium/infrastructure/issues/3217 (For Windows only)
Related https://github.com/adoptium/infrastructure/pull/3780 which is required to keep the image up to date with the playbooks

Related: The docker file used for creating this image is https://github.com/adoptium/infrastructure/blob/master/ansible/docker/Dockerfile.win2022

Also for reviewers: I'd much rather rename this credential prior to making this live since it might get mistaken for an actual credential (It's not - it's the ID/label in our jenkins instance of the stored credential)

Also FYI @AdamBrousseau for awareness. This is likely the final step in making our Windows Temurin builds run as well as they can in containers, and make it consistent with the Linux builds.

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by sxa** [comment]
run tests

**Review by karianna — APPROVED** [review]

**Comment by sxa** [comment]
Shame on both reviewers for not spotting the typo ;-) `windows2022_build_iamge` instead of `windows2022_build_image`. Take 2!

**Comment by sxa** [comment]
run tests

**Comment by sxa** [comment]
On a separte note ... Grrr @ BlueOcean for not showing the windows blob as "red" https://ci.adoptium.net/blue/organizations/jenkins/build-scripts-pr-tester%2Fbuild-test%2Fopenjdk21-pipeline/detail/openjdk21-pipeline/86/pipeline
image

**Comment by sxa** [comment]
Latest set of tests seemed to still be trying to pull `adoptium.azurecr.io/windows2022_build_iamge` for some reason despite this PR having been updated to correct that so I'll try again

**Comment by sxa** [comment]
run tests

**Pull request merged**
