### PR TITLE
Enable time based parallel

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/adoptium/ci-jenkins-pipelines/issues/1032

### CODE REVIEW

**Comment by llxia** [comment]
@smlambert @sophia-guo could you please review?

FYI @pshipton @AdamBrousseau

**Comment by llxia** [comment]
The above[ Linter job](https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/9209905011/job/25335599853?pr=1037) failure is unrelated to this PR. It failed due to `Failed to call GitHub Status API`

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
@llxia Linter unhappy

**Comment by llxia** [comment]
@karianna The above[ Linter job](https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/9209905011/job/25335599853?pr=1037) failed with `Failed to call GitHub Status API`. Any idea how to retrigger it? Force push?

**Pull request merged**
