### PR TITLE
Set propagate to true for AQA test builds

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/adoptium/ci-jenkins-pipelines/issues/234
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
@smlambert @sophia-guo could you review it? Thanks

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
Set AQA test builds `propagate to true` can propagate AQA tests result to build jobs, i.e., jdk**-**_temurin job), which will not propagate result to Adoptium top-level pipeline build. https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/build_base_file.groovy#L772.

**Review by smlambert — CHANGES_REQUESTED** [review]
Before this gets merged, I would like to talk about the side-effects.

**Comment by smlambert** [comment]
In discussion with @sophia-guo , wondering about whether this then means:
- that the parent will not archive the build artifacts
- if we change the pipeline status (not just build job status) whether it means that other child jobs will not get run

**Comment by llxia** [comment]
Is there a way for us to run a test build to confirm at Adoptium Jenkins?

**Comment by llxia** [comment]
Close this PR until we find a better solution for this.

**Pull request closed without merging**
