### PR TITLE
Use parameter releaseType to pass to downstream

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Rather than hardcoding 'Weekly', use the build parameter.

### CODE REVIEW

**Comment by smlambert** [comment]
> If this is the weekly config is it not OK to hard code that?

In https://github.com/adoptium/ci-jenkins-pipelines/issues/847 we have introduced a new job type for releases, so now there are "nightly", "weekly" and "release" types.  The name of the file is now a misnomer, weekly_release_pipeline can be used for weekly runs or release runs and it can take different job types now.

**Comment by AdamBrousseau** [comment]
>If this is the weekly config is it not OK to hard code that?

It is already hardcoded in the build_pipeline_generator.groovy
https://github.com/adoptium/ci-jenkins-pipelines/blob/833a06de53ae21ffec043863600a88a5dbbb6529/pipelines/build/regeneration/build_pipeline_generator.groovy#L265

This sets the default param value for the weekly pipelines to `releaseType=Weekly`. If a build is launched from the weekly pipeline and releaseType param is changed, it has no effect. Perhaps by design? But a little misleading I think.

**Review by adamfarley — CHANGES_REQUESTED** [review]
The code looks good. Can we amend the comment about "create a weekly pipeline job" to reflect this change, please?

**Review by sxa — COMMENTED** [review]
Can you redo the commit message to include the `e` in the middle of `releaseType` please?

**Comment by karianna** [comment]
> > If this is the weekly config is it not OK to hard code that?
> 
> In #847 we have introduced a new job type for releases, so now there are "nightly", "weekly" and "release" types. The name of the file is now a misnomer, weekly_release_pipeline can be used for weekly runs or release runs and it can take different job types now.

We should probably rename weekly config files to what they really are in that case :-)

**Comment by AdamBrousseau** [comment]
I'll further explain my use case.
We (IBM) do not publish our nightly/weekly build. So we've always run "nightly without publish" and "weekly without publish". I've reconfigured our regenration code to make the defaults "* without publish". I recently made a change to properly set the config rather than just reordering the drop down list in the build launch (see https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/188). In doing so, we're relying on the parameter passed from the weekly build to the regular build, which up until this PR, has been ignored because it takes the hardcoded "Weekly". So, we are not reinventing the weekly build (wrapper job) into something else, we are simply using it "without publish". Arguably, the publish should be a separate boolean and not part of the release type. But that is a different topic.

**Comment by smlambert** [comment]
For the record, I agree with you on the cleaner design of separate boolean param for 'publish', but as you say, its outside of the scope of this PR.

**Review by adamfarley — APPROVED** [review]
LGTM, thanks for changing the comment. :)

**Pull request merged**
