### PR TITLE
feat: enable sign and installer for pr-test

### PR DESCRIPTION
**Pull request by zdtsw**
- to be able to test not only generation + build jobs but also sign and installer steps

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
@sxa @gdams before we change this, is there any reason the PR tester does not currently run the sign and installer steps?

**Comment by gdams** [comment]
run tests

**Comment by zdtsw** [comment]
> #  PR TESTER RESULT 
> negative_squared_cross_mark Some pipelines failed or the job was aborted! negative_squared_cross_mark _See the `pipeline-build-check` below for more information..._

**jdk17** failed on aarch64: ERROR: Build failed due to downstream failure of build-scripts-pr-tester/build-test/jobs/jdk17u/jdk17u-linux-aarch64-temurin
re-run job passed https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk17u/job/jdk17u-linux-aarch64-temurin/65/ on a different agent.

the failed one https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk17u/job/jdk17u-linux-aarch64-temurin/64 was due to a crap ec2.... but how, do we have ec2 fleet plugin enabled ? 
Screenshot from 2022-08-18 08-06-45

**jdk19** failed on https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk19/job/jdk19-alpine-linux-x64-temurin/53/console which is an unknown issue https://adoptium.slack.com/archives/CFUJV9XV0/p1660732282071019

**Comment by zdtsw** [comment]
re-run jdk19 alpine after removed duplicated binary, passed.

**Comment by sxa** [comment]
> @sxa @gdams before we change this, is there any reason the PR tester does not currently run the sign and installer steps?

I would imagine speed.

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by zdtsw** [comment]
need another approval if we agree to proceed with this change

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
