### PR TITLE
Set system.dev with additional label and vendors info

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix issues mentioned in https://github.com/adoptium/temurin-build/issues/3587

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by karianna — CHANGES_REQUESTED** [review]
/github/workspace/pipelines/build/common/openjdk_build_pipeline.groovy
  401   error    The current scope already contains a variable of the name vendorTestBranches
 @ line 401, column 33.  NglParseError           
  402   error    The current scope already contains a variable of the name vendorTestRepos
 @ line 402, column 33.  NglParseError

**Comment by sophia-guo** [comment]
Updated @karianna

**Review by karianna — APPROVED** [review]

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Now #929 is merged, this can come in, needs a rebase @sophia-guo

**Comment by sophia-guo** [comment]
Didn't realize that this PR is not merged until I noticed the issue with https://ci.adoptium.net/job/Test_openjdk23_hs_dev.system_x86-64_linux/3/.

Rebased.

**Pull request merged**
