### PR TITLE
Fix missing wildcard in os/arch/variant pattern match

### LINKED ISSUE #887: Builds are failing to copy artifacts, Dubious character in TARGET_OS, ARCHITECTURE or VARIANT
We're seeing an error during the copy artifacts stage of all of the dry run builds

```
19:00:29  ERROR: Error during copy and archive artifacts for build job: build-scripts/jobs/release/jobs/jdk17u/jdk17u-release-linux-arm-temurin
19:00:29  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 5d6e732e-7498-48f9-840e-80a12f077405
19:00:29  java.lang.Exception: [ERROR] Dubious character in TARGET_OS, ARCHITECTURE or VARIANT - aborting
```

eg https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/50/console

Error can be traced to here:
https://github.com/adoptium/ci-jenkins-pipelines/blob/c58042b6667e06360a56ea80a10d7d3fd7c490d0/pipelines/build/common/build_base_file.groovy#L912

Likely introduced by this pr https://github.com/adoptium/ci-jenkins-pipelines/pull/873

### PR DESCRIPTION
**Pull request by sxa**
Fixes #887, introduced by #873
Will need to be cherry picked across to the v2024.01.01 branch once approved

### CODE REVIEW

**Review by Haroon-Khel — APPROVED** [review]

**Comment by sxa** [comment]
/approve
(Can I do it to my own pr?)

**Review by gdams — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
After this gets cherry picked into v2024.01.01 ill kick off dry runs for jdk8 arm32

**Pull request merged**
