### PR TITLE
Set jdk8 arm publishName

### LINKED ISSUE #700: ci pipelines do not check overridePublishName is set for jdk8u aarch32 Release
Ref issue: https://github.com/adoptium/adoptium/issues/225#issuecomment-1527435352
When doing the release pipeline for jdk8u aarch32 it is easy to forget to specify overridePublishName

### PR DESCRIPTION
**Pull request by sophia-guo**
- Set jdk8 arm publishName
- Remove over overridePublishName from release pipeline job

Fix #700 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM although it removes functionality that others might use?

**Review by andrew-m-leonard — APPROVED** [review]
lgtm, although we ought to also update the RELEASE.md and remove overridePublishName: https://github.com/adoptium/temurin-build/blob/master/RELEASING.md

**Review by smlambert — APPROVED** [review]

**Comment by sophia-guo** [comment]
@AdamBrousseau Does or will openj9 use [release_pipeline_job_template.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/release_pipeline_job_template.groovy) to generate pipeline jobs? Suppose right now [pipeline_job_template.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/pipeline_job_template.groovy) is used?

**Comment by AdamBrousseau** [comment]
Semeru does not use the release job template yet. No plans to as of now.

**Pull request merged**
