### PR TITLE
Clean controller node workspace before and after doing a pipeline build

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Clean the pipeline Jenkins controller worker "workspace" prior and after running the pipeline builds. This ensure we don't excessively use disk storage unnecessarily.

Fixes https://github.com/adoptium/ci-jenkins-pipelines/issues/426

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
@sxa Once this is merged, we can delete these workspaces: https://github.com/adoptium/ci-jenkins-pipelines/issues/426#issuecomment-1267134239
which should free up about 128Gb

**Review by zdtsw — APPROVED** [review]

**Review by sxa — APPROVED** [review]
LGTM as far as I can see. In terms of deleting the existing workspaces, presumably they will naturally delete themselves in the next few days once this is in place so leaving them to do so will prove whether this fix has worked in all cases :-)

FYI @karianna sine we've discussed jenkins pipeline space usage in the past (usually when we've had to increase it on the jenkins server) this should reduce the amount of temporary space being used significantly.

**Comment by andrew-m-leonard** [comment]
> LGTM as far as I can see. In terms of deleting the existing workspaces, presumably they will naturally delete themselves in the next few days once this is in place so leaving them to do so will prove whether this fix has worked in all cases :-)
> 

@sxa It will mostly delete the main ones, but there are some @2 workspaces that may take a while to get deleted, eg.:
```
ls -l /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/build-test
total 64
drwxr-xr-x 7 jenkins ciagent 4096 Sep 30 09:21 jobs
drwxr-xr-x 3 jenkins ciagent 4096 Sep 29 07:59 openjdk11-pipeline@2
drwxr-xr-x 2 jenkins ciagent 4096 Sep 29 08:00 openjdk11-pipeline@2@tmp
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 17:13 openjdk11-pipeline@tmp
drwxr-xr-x 3 jenkins ciagent 4096 Sep 30 08:20 openjdk17-pipeline@2
drwxr-xr-x 2 jenkins ciagent 4096 Oct  1 13:41 openjdk17-pipeline@2@tmp
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 16:56 openjdk17-pipeline@tmp
drwxr-xr-x 3 jenkins ciagent 4096 Oct  4 16:05 openjdk18-pipeline@2
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 16:07 openjdk18-pipeline@2@tmp
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 16:53 openjdk18-pipeline@tmp
drwxr-xr-x 3 jenkins ciagent 4096 Oct  4 09:43 openjdk19-pipeline@2
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 09:44 openjdk19-pipeline@2@tmp
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 17:01 openjdk19-pipeline@tmp
drwxr-xr-x 3 jenkins ciagent 4096 Sep 30 09:49 openjdk8-pipeline@2
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 15:35 openjdk8-pipeline@2@tmp
drwxr-xr-x 2 jenkins ciagent 4096 Oct  4 16:13 openjdk8-pipeline@tmp
```

**Comment by sxa** [comment]
Looking good at the moment - 62GB free and "only" 92GB in use by jenkins this morning.

**Pull request merged**
