### PR TITLE
Added JMH to be also built by code-tools

### PR DESCRIPTION
**Pull request by judovana**
JMH is another code-tools openjdk project which release pretty randomly.
JMH suite itslef is engine to run benchamrks,  and reelased versions are apearing in maven repos (similarly as jcstress).
JMH samples can be used as pretty good testsuite when reduced to run minimal iterations.

Generally spoken the build of TIP is heavily missed world wide.

### CODE REVIEW

**Comment by karianna** [comment]
Is this actually required.  Aleksey regularly releases this upstream

**Comment by judovana** [comment]
> Is this actually required. Aleksey regularly releases this upstream

I wish it is not requored:(

https://github.com/openjdk/jmh/tags - year ago 
followed by https://github.com/openjdk/jmh/tags

But true - latest released is brobably not necessary. only tip.

**Comment by judovana** [comment]
Actually one reason to build both master and latest released - if the build of tip fails, it may behard to say it it is jdk or jmh who isguilty. If fails latest released, then it is most likely jdk.

**Comment by gdams** [comment]
ping @shipilev to see whether he does plan to continue building this or not

**Comment by sophia-guo** [comment]
Is this still in progress as jenkinsfile also need to update if we'd like to build here?

**Comment by judovana** [comment]
> Is this still in progress as jenkinsfile also need to update if we'd like to build here?

Nope. sorry. I forget about it.

**Comment by shipilev** [comment]
The overwhemling majority of users consume JMH through Maven Central releases. So, unless you are planning to publish SNAPSHOT versions somewhere, I see no particular value in building JMH separately in Adoptium. I see no particular cost for it either, so it is your choice, really.

**Review by sophia-guo — APPROVED** [review]

**Comment by judovana** [comment]
tyvm!

**Review by smlambert — APPROVED** [review]

**Pull request merged**
