### PR TITLE
fix: use `actions/labeler@v5` config file format

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR adapts the labeler config file to the new format introduced in version 5.

Related to:
- #855

### CODE REVIEW

**Comment by lemeurherve** [comment]
I signed-off my commit with the mail I've used to create my Eclipse account and sign the ECA, I don't know what to do more.

**Comment by karianna** [comment]
@lemeurherve I revalidated the signing process so that passes now.  Reading the labeler documentation tells me your change is likely correct but it's hard to tell since pull_request_target only runs against the base branch.  I'll merge this as it's a step in the right direction.

**Review by karianna — APPROVED** [review]
This is a step in the right direction

**Comment by karianna** [comment]
Needs one more approval

**Review by smlambert — APPROVED** [review]

**Pull request merged**
