### PR TITLE
Enable regular nightly and weekly build for jdk21

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
@andrew-m-leonard is it a good time to enable the regular nightly and weekly build for jdk21?

**Comment by sxa** [comment]
I believe the intention is to only use the trigger job going forward - there should be no need to have this running on a more regular cadence, since it will be triggered with all applicable jobs on each new tag appearing.

Also at the moment (while we don't have a JDK21 GA on all platforms) we need to avoid publishing new nightlies for JDK21 so that the EA level that we've been pointing people at is still the one based off jdk-21+35.

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard is it a good time to enable the regular nightly and weekly build for jdk21?

Yes, as per @sxa comment.
The jdk21u EA builds will trigger from here https://ci.adoptium.net/job/build-scripts/job/utils/job/releaseTrigger_21ea/
which is currently disabled as per Stewart's comment

**Comment by sxa** [comment]
Having said that I do now have a concern that with no new tags being created in jdk21u perhaps there is justification for having this on some regular basis for jdk21u specifically (maybe just the weekly) but perhaps without publishing

**Comment by andrew-m-leonard** [comment]
Yeah, until Oracle hand over jdk-21.0.2 to SAP in January there will be no regular build tags, and jdk1u will contain a mix of jdk-21.0.1 and 21.0.2 commits

**Comment by sophia-guo** [comment]
Dup of https://github.com/adoptium/ci-jenkins-pipelines/pull/834. Close it.

**Pull request closed without merging**
