### PR TITLE
Remove assign to project workflow

### PR DESCRIPTION
**Pull request by gdams**
This has been broken for some time since we moved to zenhub

### CODE REVIEW

**Comment by karianna** [comment]
GH action still failing?

**Comment by gdams** [comment]
> GH action still failing?

@karianna it will only stop failing once the change has been merged

**Comment by karianna** [comment]
PMC approved - about time we got back to green on GH actions

**Review by karianna — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]

**Pull request merged**
