### PR TITLE
Add dev.system for aarch64_mac for jdk21+

### PR DESCRIPTION
**Pull request by sophia-guo**
related https://github.com/adoptium/temurin-build/pull/3972

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by steelhead31 — APPROVED** [review]
Looks good.

**Pull request merged**
