### PR TITLE
rip out duplicate jenkins helper library

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Extended draft PR from : https://github.com/adoptium/ci-jenkins-pipelines/pull/348

Fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/313

Remove the hard coded loading of a Jenkins helper library from pipelines/library, move those functions to the existing properly configured openjdk-jenkins-helper.

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by gdams — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
> This seems to be duplicating @gdams work?

@karianna yes, see conversation: https://adoptium.slack.com/archives/C09NW3L2J/p1657020006328629?thread_ts=1657010752.454829&cid=C09NW3L2J

**Review by karianna — APPROVED** [review]
LGTM

**Comment by andrew-m-leonard** [comment]
jdk8u win64 failure is locked file issue on GPG sign, not related to this PR. Re-run passed.

**Pull request merged**
