### PR TITLE
rip out duplicate jenkins helper library

### PR DESCRIPTION
**Pull request by gdams**
fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/313

CC @AdamBrousseau

### CODE REVIEW

**Comment by karianna** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/issues/345

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by zdtsw** [comment]
still  keep testcases in this repo, not moving to "helper" ?

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by gdams** [comment]
closing in favour of #355

**Pull request closed without merging**
