### PR TITLE
feat: trim string in put parameters from build job

### PR DESCRIPTION
**Pull request by zdtsw**
- add test case
	- use a wrapper to handle trim before return constructor
	

Ref: #289

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM in principle.

**Comment by zdtsw** [comment]
@andrew-m-leonard can I get review on this PR?

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by zdtsw** [comment]
`Scripts not permitted to use method java.util.Map$Entry setValue java.lang.Object` does it mean we need to approve in-process script in Jenkins?

**Comment by andrew-m-leonard** [comment]
@zdtsw i've just approved it, will re-run

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
@zdtsw unsure why this is failing?
```
java.lang.Exception: [ERROR] Failed to create IndividualBuildConfig for platformConfig: [os:linux, arch:x64, dockerImage:adoptopenjdk/centos6_build_image, dockerFile:[openj9:pipelines/build/dockerFiles/cuda.dockerfile, dragonwell:pipelines/build/dockerFiles/dragonwell.dockerfile], test:default, configureArgs:[openj9:--enable-jitserver, dragonwell:--enable-unlimited-crypto --with-jvm-variants=server  --with-zlib=system], buildArgs:[temurin:--create-source-archive]].
java.lang.UnsupportedOperationException
	at Regeneration.buildConfiguration(Script3.groovy:451)
	at Regeneration.regenerate(Script3.groovy:689)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2068)
	at Regeneration.regenerate(Script3.groovy:674)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2068)
	at Regeneration.regenerate(Script3.groovy:660)
```

**Comment by zdtsw** [comment]
> @zdtsw unsure why this is failing?
> 
> ```
> java.lang.Exception: [ERROR] Failed to create IndividualBuildConfig for platformConfig: [os:linux, arch:x64, dockerImage:adoptopenjdk/centos6_build_image, dockerFile:[openj9:pipelines/build/dockerFiles/cuda.dockerfile, dragonwell:pipelines/build/dockerFiles/dragonwell.dockerfile], test:default, configureArgs:[openj9:--enable-jitserver, dragonwell:--enable-unlimited-crypto --with-jvm-variants=server  --with-zlib=system], buildArgs:[temurin:--create-source-archive]].
> java.lang.UnsupportedOperationException
> 	at Regeneration.buildConfiguration(Script3.groovy:451)
> 	at Regeneration.regenerate(Script3.groovy:689)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2068)
> 	at Regeneration.regenerate(Script3.groovy:674)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
> 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2068)
> 	at Regeneration.regenerate(Script3.groovy:660)
> ```

Checking this, might be something when I chagned buildConfiguration() return

**Comment by zdtsw** [comment]
with a different implementation, which I originally thought was ugly but seems the most straightforward way to do it. https://github.com/adoptium/ci-jenkins-pipelines/pull/295
so I have this one closed for now, till I have local groovy test env. setup then can debug a bit more.

**Pull request closed without merging**
