### PR TITLE
Revert "Pipeline Triggers instead of triggers" for Jenkinsfile

### PR DESCRIPTION
**Pull request by M-Davies**
* Properties and pipelineTriggers does not exist for this type of job

Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
The error in question
```
WorkflowScript: 8: The ‘properties’ section has been renamed as of version 0.8. Use ‘options’ instead. @ line 8, column 5.
       properties {
```

**Review by gdams — APPROVED** [review]

**Comment by karianna** [comment]
Probably unrelated - but can this get resolved?

```
/usr/bin/docker run --name e4c5fc78e3914744ee9731603a9c7a5e38_6988da --label 5588e4 --workdir /github/workspace --rm -e INPUT_PROJECT -e INPUT_COLUMN_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ci-jenkins-pipelines/ci-jenkins-pipelines":"/github/workspace" 5588e4:c5fc78e3914744ee9731603a9c7a5e38  "https://github.com/adoptium/ci-jenkins-pipelines/projects/1" ""
GITHUB_TOKEN not defined
```

**Comment by karianna** [comment]
Ah NM, I see its fixed in another PR.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
I think you'll be able to use the newer syntax when we roll out a brand new Jenkins at Adoptium.

**Pull request merged**
