### PR TITLE
Disable jdk17 reproducible comparison builds

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
There's no description or issue reference on this PR - why are we disabling it?

**Comment by andrew-m-leonard** [comment]
I realise the jdk17u compares have been red for a while, and we need to have a look at them, but is there another reason to remove them?

**Comment by sophia-guo** [comment]
@jiekang mentioned it's not needed anymore for 17 and we only need to focus on 21.

**Comment by sxa** [comment]
Given the amount of work we've put into backporting stuff into the 17 codebase I'm personally very much -1 on this unless we are actively choose to avoid maintaining it.

**Comment by sophia-guo** [comment]
Based on the discussion we will hold it off for now

**Pull request closed without merging**
