### PR TITLE
Update jdk23 and add jdk24 pipeline configurations

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
- Add new jdk24 pipeline configuration files, now that jdk23 has branched.
- Add jdk23_release.groovy, and remove obsolete arm32, win32, and remove riscv from evaluation.

Note: Had to fix build_base_file.groovy, as the pr-tester is failing due to missing logic for AQAvit archiving when no AQA tests are run...

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
Looks ok.

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by sxa — COMMENTED** [review]
We should hold off on this until https://github.com/adoptium/ci-jenkins-pipelines/pull/1045 is merged, and then rebase on that change to ensure that the AIX changes are included here.

**Comment by sxa** [comment]
AIX PRs merged, so if you can add in the label changes to the new versions in this PR that would be appreciated :-)

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
> AIX PRs merged, so if you can add in the label changes to the new versions in this PR that would be appreciated :-)

@sxa updated..

**Review by sxa — APPROVED** [review]
LGTM :-)

**Pull request merged**
