### PR TITLE
Define Apple Silicon build job

### PR DESCRIPTION
**Pull request by aahlenst**
I'm starting to line up the necessary PRs.

 Biggest question: How do we want to call the architecture? `arm` (as in `uname -p`) or `arm64` (as in `uname -m`) or something else?

### CODE REVIEW

**Comment by VladimirKempik** [comment]
jdk buildsys uses combo "macosx-aarch64" to define this config, you might want to stay aligned with that to prevent possible mess up

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Review by gdams — APPROVED** [review]

**Pull request merged**
