### PR TITLE
feat: disable hotspot being built in jdk19 weekly pipeline

### PR DESCRIPTION
**Pull request by zdtsw**

### CODE REVIEW

**Review by karianna — APPROVED** [review]
lgtm

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by zdtsw** [comment]
@sxa up to you if you want to keep "hotspot" or not , ref [Add in one 'hotspot' variant build for JDK head ](https://github.com/adoptium/ci-jenkins-pipelines/pull/251)

**Comment by sxa** [comment]
> @sxa up to you if you want to keep "hotspot" or not , ref [Add in one 'hotspot' variant build for JDK head ](https://github.com/adoptium/ci-jenkins-pipelines/pull/251)

I think it makes sence purely  to verify that no changes we make to the scripts 'break' the end-user use case of buiding hotspot from a clean hotspot codebase. When I initially suggested removing it I thought it was enabled more universally, but if it's just for aarch64 (Which is fast to build and we have lots of available CPU capacity) I think my preference would be to leave it in.

**Comment by zdtsw** [comment]
close this PR (see detail reason above)

**Pull request closed without merging**
