### PR TITLE
Add check for JDK_OPENJ9_BRANCH

### PR DESCRIPTION
**Pull request by llxia**
cherry-pick: https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/116

fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/597

Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
@smlambert @sophia-guo could you please review?

FYI @AdamBrousseau

**Comment by llxia** [comment]
[internal Semeru build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/openjdk8-pipeline/636/console)

```
+ curl -Os https://raw.githubusercontent.com/adoptium/aqa-tests/v0.9.6-release/testenv/testenv.properties
[Pipeline] readFile
[Pipeline] echo
[INFO] scmReference=v0.36.0-release matches with JDK8_OPENJ9_BRANCH=v0.36.0-release in testenv.properties in aqa-tests release branch.
```

**Review by smlambert — APPROVED** [review]
👍

**Comment by smlambert** [comment]
As we are using a release branch now instead of master, this can safely be merged without affecting the ongoing release activities.

**Pull request merged**
