### PR TITLE
Extending test timeout on slow platforms

### PR DESCRIPTION
**Pull request by adamfarley**
Some platforms can take over 10 hours to run a full suite of extended.openjdk tests, even when split between 3 parallel machines.

Therefore we should extend the timeout to allow the tests to run to completion.

### CODE REVIEW

**Comment by adamfarley** [comment]
Fixes https://github.com/adoptium/ci-jenkins-pipelines/issues/852

**Review by karianna — APPROVED** [review]

**Review by sxa — APPROVED** [review]
Anything further needed for this to have the WIP prefix removed?

**Comment by adamfarley** [comment]
Just a successful test run. Whether it prevents the issue or not, I want to be sure this hasn't broken anything.

**Comment by adamfarley** [comment]
> > Just a successful test run. Whether it prevents the issue or not, I want to be sure this hasn't broken anything.
> 
> While you're waiting - any chance you can adjust the commit message to call out s390x and riscv64 explicitly - it can be really useful when searching commit messages in the future.

Sure, done.

**Comment by karianna** [comment]
@adamfarley Is that a manual test run or since hte GH Action Checks have passed we can merge this?

**Comment by adamfarley** [comment]
> @adamfarley Is that a manual test run or since hte GH Action Checks have passed we can merge this?

It's a manual test run referred to in the issue [here](https://github.com/adoptium/ci-jenkins-pipelines/issues/852#issuecomment-1927263574).

Unfo0rtunately the change does not appear to be working. I'm looking into it now.

**Comment by adamfarley** [comment]
Ok, here's a rerun with some debug messages:

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-s390x-temurin/16/

And here's a rerun using the upstream pipeline job, in case this is one of those things that's outside the scope of the job parameters.

https://ci.adoptium.net/job/build-scripts/job/openjdk22-pipeline/118/

**Comment by adamfarley** [comment]
Ok, I've put in the fix for the TIME_LIMIT-not-being passed downstream issue, and I've refined the formatting.

If this job passes the variable correctly, we're good to merge.

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-s390x-temurin/20/

**Comment by adamfarley** [comment]
Variable passes correctly. Good to go. Requesting a re-review as the code was changed significantly after the last reviews.

**Comment by adamfarley** [comment]
Okie dokie, will make another PR.

**Pull request merged**
