### PR TITLE
Do not issue docker pull if imagename contains rhel

### PR DESCRIPTION
**Pull request by sxa**
rhel images cannot be uploaded to dockerhub, so this is a test to see if we can use a local image on the machine. A final solution is likely to involve pushing it into a credentials-protected location, or having an additional parameter to skip the pull operation but that can be done as a subsequent step.

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
This didn't work https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk17u/job/jdk17u-linux-x64-temurin/109/console (Note that that job was run with labels for `s390x` not `x86-64`

**Comment by sxa** [comment]
run tests

**Comment by sxa** [comment]
Taking out of draft now that the UID problem referred to in https://github.com/adoptium/infrastructure/issues/2731#issuecomment-1456243992 - https://github.com/adoptium/infrastructure/pull/2982 now creates the jenkins user with the UID expected on our Marist s390x systems and can complete builds.

**Comment by sxa** [comment]
@andrew-m-leonard How can I re-run the failing check? Just doing a straight rebuild of the jenkins job [doesn't seem to work](https://ci.adoptium.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/1807/console)

**Comment by sxa** [comment]
This looks like it might be a failure in the SBOM generation on macos: https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk17u/job/jdk17u-mac-x64-temurin/96/console
```
11:21:07  build:
11:21:07       [echo] Building cyclonedx-lib
11:21:07  
11:21:07  BUILD SUCCESSFUL
11:21:07  Total time: 7 seconds
11:21:07  Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector
11:21:07  	at org.cyclonedx.BomGeneratorFactory.createJson(BomGeneratorFactory.java:65)
11:21:07  	at temurin.sbom.TemurinGenSBOM.generateBomJson(Unknown Source)
11:21:07  	at temurin.sbom.TemurinGenSBOM.writeJSONfile(Unknown Source)
11:21:07  	at temurin.sbom.TemurinGenSBOM.main(Unknown Source)
11:21:07  Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.AnnotationIntrospector
```
(Annoyingly it's quite non-obvious from the check job which bit is failing as they all show as green in the blue ocean view)

**Comment by andrew-m-leonard** [comment]
That's weird, is that SBOM failure repeatable? If you re-run the github CI build pipeline task?

**Comment by sxa** [comment]
> That's weird, is that SBOM failure repeatable? If you re-run the github CI build pipeline task?

What do you mean by `github CI build pipeline task`? If I click the Details link on `pipeline-build-check` it takes me straight to jenkins.

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
> > That's weird, is that SBOM failure repeatable? If you re-run the github CI build pipeline task?
> 
> What do you mean by `github CI build pipeline task`? If I click the Details link on `pipeline-build-check` it takes me straight to jenkins.
> 
> As per [earlier comment](https://github.com/adoptium/ci-jenkins-pipelines/pull/611#issuecomment-1456340749) I can't just click rebuild on the job in jenkins :-(

Yeah sorry meant "run tests" for this one

**Comment by sxa** [comment]
> Yeah sorry meant "run tests" for this one

👍🏻 xlinux failed this time but that's a known issue which has now been resolved so I'll re-trigger

**Comment by sxa** [comment]
run tests

**Comment by gdams** [comment]
Noting that we already pull with credential, why don’t you just push to dockerhub and mark it as private? Seems less prone to errors and requires no additional code changes

**Comment by gdams** [comment]
Frustrating that this PR was merged without a response to my query, this seems like a completely unnecessary code change to solve a problem that doesn't exist.

**Comment by sxa** [comment]
Apologies for missing your comment on this occasion. Feel free to submit a follow-on in order to change the mechanism.

**Pull request merged**
